name: CI/CD pipline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push-to-dh:
    name: Build and push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build docker rec image
        run: |
          docker build . -f ./rec-service/Dockerfile --tag uzorovkirill/maprac6-rec:latest


      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and push rec service image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/maprac6-rec:latest
  

  build-and-push-to-yc:
    name: Build and push to YandexCloud Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        run: |
          docker build . -f ./book-service/Dockerfile --tag cr.yandex/${{ secrets.YC_REGISTRY_ID }}/book-service:latest

      - name: Login to YC Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_KEYS }}

      - name: Push tag YC Registry
        run: |
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/book-service:latest


